### ISSUE TITLE
Installer script broke the OS; cannot reboot

### ISSUE THREAD

**Issue by coochewgames** [timskillman/Pi3C#3]
After running the Installer script in a Pi 0, it installed a whole bunch of rpihacks then when rebooted, it does not complete.  The screen goes black at different points of the boot up but doesn't complete.

**Comment by timskillman** [comment]
Hi coochewgames - the installer script doesn't install rpihacks AFAIK.

If you take a look at 'Installer.sh' it does the following;

1) Installs latest SDL2.0 libraries including Mixer, TTF, Image and Net (lines 9-12)
2) Checks for Pi version (pione, pitwo, pizero, pifour) - (lines 14-37)
3) Sets the OpenGL driver (lines 39-66)
4) Sets the OpenGL memory GPU memory split to 64Mb (lines 69-78)
5) Reboots

There's no other download to install hacks and it's all based on the RpiConfig utility

I'll add the manual instructions into the repo again - this installer basically replaced those to make it simple.
Thanks for your feedback

**Comment by kbar-sys** [comment]
Yes I did notice the Installer ran a bunch of updates, also affecting interim pauses on my Zero 1. To name some that installed - opus, harfbuzz, gio, zstd, ibus, deflate, sysprof, graphite2, xxx123, sharpyuv, blkid, webp and pulse. None of these are mentioned in the manual setup docs.

**Comment by kbar-sys** [comment]
As a note: I've reinstalled RaspberryOS Lite after running Installer.sh and when I have tried to install other libraries on a new OS I am now seeing extra packages needing to be downloaded that are not on the Debian libsdl2 site: https://packages.debian.org/sid/libsdl2-dev

**Comment by kbar-sys** [comment]
Also on the Trixie site: https://packages.debian.org/source/trixie/libsdl2

**Comment by kbar-sys** [comment]
I used Co-pilot and I have found this helpful - "when you install a minimal desktop environment on Raspberry Pi OS Lite, it requires additional system libraries that aren't present in the headless version. Graphics libraries like the SDL2 packages have dependencies that cascade down the system. When apt-get resolves those dependencies, it pulls in supporting libraries like libblkid (which handles block device identification for the display system and other hardware components)"

Also this - "I found the installer script. Looking at the code, the issue is that the Installer.sh script only installs SDL 2.0 libraries, which are the actual project dependencies"
