### ISSUE TITLE
[General Question] What is the contribution policy for things using the Standard Library?

### ISSUE THREAD

**Issue by alexshirley** [timskillman/Pi3C#4]
Hiya!

Just wondering what the policy is regarding using things like the STL. There appear to be a handful of easy cleanups could be made with standard algorithms.

**Comment by alexshirley** [comment]
Hey Tim!

Anywhere where a for-loop might lend better (it's been a few months since I've looked at the Pi3C)

but for example, instead of using something like:

```
for (int i = 0; i < x; i++){
    ... // doing a transform
    if (transformed_variable_based_on_indexed_array == something)
        return true;
}
return false;
```

this is a std::any_of

```
return std::any_of(array.begin(), array.end(), [](auto const item){
    return transformation_fxn(item);
});
```

likewise instead of updating a variable

```
auto temp = 0;
for (int i = 0; i < x; i++){
    if (a[i] > temp) temp = a[i];
}
```

This is a std::max_element

```
return *std::max_element(a.begin(), a.end());
```

There are some small snags since custom strides are used everywhere, but I can work around that with custom iterators.

Anyway, what do you think? The goal is improve readability, but generally standard calls are as fast or faster than hand-written loops.

**Comment by timskillman** [comment]
Hi Alex,

Sounds great!  You're very welcome to fork Pi3C and submit changes for it
to be merged back :)

Pi3C has been developed on and off over the years and still is - the aim is
to develop a lightweight engine for Apps and Games that would run on a Pi
Zero (and equivalent).
I hope to develop Apps that are powerful, such as the 3D modeler for
example; using 3D tools like Boolean and point/patch editing - so that
complex (but low-poly) objects can be created easily.
Or Games, like mine-craft, that can be customized with mobs etc..

Anyway, I really welcome any help you might want to offer and I will credit
you with your changes :)

Kind regards,

Tim
